### ISSUE TITLE
IE9 error

### ISSUE THREAD

**Issue by lswamy** [zuulinc/simpleload#1]
IE9 outputs the following error message for line 27 character 23:

SCRIPT5007: Unable to get value of the property 'items': object is null or undefined

**Comment by lswamy** [comment]
attached is an example that outputs errors in IE9

[simpleload-test.zip](https://github.com/zuulinc/simpleload/files/66838/simpleload-test.zip)

**Comment by kpjf** [comment]
Looking at it now.

**Comment by kpjf** [comment]
What OS are you running IE9 on?

**Comment by lswamy** [comment]
My tests are on the Microsoft VM image with IE9 on Windows 7.

**Comment by kpjf** [comment]
I've been able to replicate and what I see is that the string is being written to the console, and then an error after that.

**Comment by kpjf** [comment]
Issue was related to both onload & readystate changed firing, I added a flag to check for callback execution status
